# Dockerfile
FROM n8nio/n8n:latest

# Opcjonalnie ustaw strefę czasową w warstwie obrazu
ENV TZ=${TZ}

# Nic nie kopiujemy – stan będzie w wolumenie ./data
# WORKDIR nie ma znaczenia dla danych n8n; n8n używa /home/node/.n8n